check_for_builtin_functions:
  comment: 'OK'
check_for_data_compression_and_archiving:
  comment: 'OK'
check_for_file_and_directory_access:
  comment: 'OK'
check_for_environment_variable_use_in_python:
  comment: 'OK'
check_python_untrusted_xml_functions:
  comment: 'OK'
check_for_supported_tls:
  comment: 'OK'
check_for_binary_files_without_source_code:
  comment: 'OK'
